# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RatShuttlingPawEventsGeneratorQt5.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RatShuttlingPawEventsGenerator(object):
    def setupUi(self, RatShuttlingPawEventsGenerator):
        RatShuttlingPawEventsGenerator.setObjectName("RatShuttlingPawEventsGenerator")
        RatShuttlingPawEventsGenerator.resize(1815, 1392)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RatShuttlingPawEventsGenerator.sizePolicy().hasHeightForWidth())
        RatShuttlingPawEventsGenerator.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RatShuttlingPawEventsGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 1052, 319, 169))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 4, 311, 158))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pB_Run = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pB_Run.setFont(font)
        self.pB_Run.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/playbuttons/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/playbuttons/Run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Run.setIcon(icon)
        self.pB_Run.setIconSize(QtCore.QSize(64, 64))
        self.pB_Run.setCheckable(True)
        self.pB_Run.setAutoExclusive(False)
        self.pB_Run.setDefault(False)
        self.pB_Run.setFlat(True)
        self.pB_Run.setObjectName("pB_Run")
        self.buttonGroup = QtWidgets.QButtonGroup(RatShuttlingPawEventsGenerator)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pB_Run)
        self.horizontalLayout_10.addWidget(self.pB_Run)
        self.pB_Stop = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pB_Stop.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/playbuttons/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/playbuttons/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Stop.setIcon(icon1)
        self.pB_Stop.setIconSize(QtCore.QSize(64, 64))
        self.pB_Stop.setCheckable(True)
        self.pB_Stop.setChecked(True)
        self.pB_Stop.setAutoExclusive(False)
        self.pB_Stop.setDefault(False)
        self.pB_Stop.setFlat(True)
        self.pB_Stop.setObjectName("pB_Stop")
        self.buttonGroup.addButton(self.pB_Stop)
        self.horizontalLayout_10.addWidget(self.pB_Stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_updates_sec = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_updates_sec.sizePolicy().hasHeightForWidth())
        self.label_updates_sec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_updates_sec.setFont(font)
        self.label_updates_sec.setObjectName("label_updates_sec")
        self.horizontalLayout_7.addWidget(self.label_updates_sec)
        self.sB_updates_sec = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sB_updates_sec.setFont(font)
        self.sB_updates_sec.setMinimum(1)
        self.sB_updates_sec.setMaximum(20)
        self.sB_updates_sec.setObjectName("sB_updates_sec")
        self.horizontalLayout_7.addWidget(self.sB_updates_sec)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(16, 1048, 171, 175))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 1, 171, 171))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pB_selecet_data = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_selecet_data.sizePolicy().hasHeightForWidth())
        self.pB_selecet_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_selecet_data.setFont(font)
        self.pB_selecet_data.setObjectName("pB_selecet_data")
        self.verticalLayout_8.addWidget(self.pB_selecet_data)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_data_loaded = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_data_loaded.setFont(font)
        self.label_data_loaded.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data_loaded.setObjectName("label_data_loaded")
        self.horizontalLayout_9.addWidget(self.label_data_loaded)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(14, 1230, 659, 99))
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(8, 4, 651, 90))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_FrameNum = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FrameNum.sizePolicy().hasHeightForWidth())
        self.label_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_FrameNum.setFont(font)
        self.label_FrameNum.setObjectName("label_FrameNum")
        self.horizontalLayout.addWidget(self.label_FrameNum)
        self.sBox_FrameNum = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBox_FrameNum.sizePolicy().hasHeightForWidth())
        self.sBox_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sBox_FrameNum.setFont(font)
        self.sBox_FrameNum.setFrame(True)
        self.sBox_FrameNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sBox_FrameNum.setSpecialValueText("")
        self.sBox_FrameNum.setKeyboardTracking(False)
        self.sBox_FrameNum.setMaximum(10000000)
        self.sBox_FrameNum.setObjectName("sBox_FrameNum")
        self.horizontalLayout.addWidget(self.sBox_FrameNum)
        self.pB_PrevFrame = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_PrevFrame.sizePolicy().hasHeightForWidth())
        self.pB_PrevFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pB_PrevFrame.setFont(font)
        self.pB_PrevFrame.setObjectName("pB_PrevFrame")
        self.horizontalLayout.addWidget(self.pB_PrevFrame)
        self.pB_NextFrame = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_NextFrame.sizePolicy().hasHeightForWidth())
        self.pB_NextFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pB_NextFrame.setFont(font)
        self.pB_NextFrame.setObjectName("pB_NextFrame")
        self.horizontalLayout.addWidget(self.pB_NextFrame)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_frames_step = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frames_step.sizePolicy().hasHeightForWidth())
        self.label_frames_step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_frames_step.setFont(font)
        self.label_frames_step.setObjectName("label_frames_step")
        self.horizontalLayout_11.addWidget(self.label_frames_step)
        self.sBox_frames_step = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBox_frames_step.sizePolicy().hasHeightForWidth())
        self.sBox_frames_step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sBox_frames_step.setFont(font)
        self.sBox_frames_step.setKeyboardTracking(False)
        self.sBox_frames_step.setMinimum(1)
        self.sBox_frames_step.setMaximum(1000)
        self.sBox_frames_step.setObjectName("sBox_frames_step")
        self.horizontalLayout_11.addWidget(self.sBox_frames_step)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(574, 1068, 155, 115))
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(4)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(2, 0, 151, 115))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_frame_resize = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame_resize.sizePolicy().hasHeightForWidth())
        self.label_frame_resize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_frame_resize.setFont(font)
        self.label_frame_resize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame_resize.setObjectName("label_frame_resize")
        self.verticalLayout_4.addWidget(self.label_frame_resize)
        self.dSB_frame_resize = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dSB_frame_resize.setFont(font)
        self.dSB_frame_resize.setDecimals(1)
        self.dSB_frame_resize.setMinimum(0.1)
        self.dSB_frame_resize.setMaximum(2.0)
        self.dSB_frame_resize.setSingleStep(0.1)
        self.dSB_frame_resize.setProperty("value", 0.5)
        self.dSB_frame_resize.setObjectName("dSB_frame_resize")
        self.verticalLayout_4.addWidget(self.dSB_frame_resize)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(768, 1052, 435, 161))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(4)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(4, 4, 294, 149))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pB_add_trial = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_add_trial.sizePolicy().hasHeightForWidth())
        self.pB_add_trial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pB_add_trial.setFont(font)
        self.pB_add_trial.setObjectName("pB_add_trial")
        self.verticalLayout.addWidget(self.pB_add_trial)
        self.pB_remove_trial = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pB_remove_trial.setFont(font)
        self.pB_remove_trial.setObjectName("pB_remove_trial")
        self.verticalLayout.addWidget(self.pB_remove_trial)
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget5.setGeometry(QtCore.QRect(304, 10, 122, 135))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_selected_trials = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selected_trials.sizePolicy().hasHeightForWidth())
        self.label_selected_trials.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_selected_trials.setFont(font)
        self.label_selected_trials.setAlignment(QtCore.Qt.AlignCenter)
        self.label_selected_trials.setObjectName("label_selected_trials")
        self.verticalLayout_9.addWidget(self.label_selected_trials)
        self.cB_selected_trials = QtWidgets.QComboBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_selected_trials.sizePolicy().hasHeightForWidth())
        self.cB_selected_trials.setSizePolicy(sizePolicy)
        self.cB_selected_trials.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cB_selected_trials.setFont(font)
        self.cB_selected_trials.setObjectName("cB_selected_trials")
        self.verticalLayout_9.addWidget(self.cB_selected_trials)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(678, 1238, 579, 85))
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(4)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, -10, 579, 97))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pB_goto_trial_frame = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_goto_trial_frame.sizePolicy().hasHeightForWidth())
        self.pB_goto_trial_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pB_goto_trial_frame.setFont(font)
        self.pB_goto_trial_frame.setObjectName("pB_goto_trial_frame")
        self.horizontalLayout_2.addWidget(self.pB_goto_trial_frame)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_trial_number_txt = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_trial_number_txt.sizePolicy().hasHeightForWidth())
        self.label_trial_number_txt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_trial_number_txt.setFont(font)
        self.label_trial_number_txt.setToolTip("")
        self.label_trial_number_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trial_number_txt.setObjectName("label_trial_number_txt")
        self.horizontalLayout_13.addWidget(self.label_trial_number_txt)
        self.label_trial_number_int = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_trial_number_int.setFont(font)
        self.label_trial_number_int.setObjectName("label_trial_number_int")
        self.horizontalLayout_13.addWidget(self.label_trial_number_int)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_trial_start_frames = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_trial_start_frames.sizePolicy().hasHeightForWidth())
        self.label_trial_start_frames.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_trial_start_frames.setFont(font)
        self.label_trial_start_frames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trial_start_frames.setObjectName("label_trial_start_frames")
        self.horizontalLayout_12.addWidget(self.label_trial_start_frames)
        self.cB_trial_start_frames = QtWidgets.QComboBox(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_trial_start_frames.sizePolicy().hasHeightForWidth())
        self.cB_trial_start_frames.setSizePolicy(sizePolicy)
        self.cB_trial_start_frames.setMinimumSize(QtCore.QSize(150, 0))
        self.cB_trial_start_frames.setMaximumSize(QtCore.QSize(150, 30))
        self.cB_trial_start_frames.setMaxVisibleItems(20)
        self.cB_trial_start_frames.setFrame(True)
        self.cB_trial_start_frames.setObjectName("cB_trial_start_frames")
        self.horizontalLayout_12.addWidget(self.cB_trial_start_frames)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_12)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(16, 980, 1353, 47))
        self.frame_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(4)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget7.setGeometry(QtCore.QRect(4, -10, 1343, 63))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_piezo_samples_to_plot = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_piezo_samples_to_plot.sizePolicy().hasHeightForWidth())
        self.label_piezo_samples_to_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_piezo_samples_to_plot.setFont(font)
        self.label_piezo_samples_to_plot.setObjectName("label_piezo_samples_to_plot")
        self.horizontalLayout_8.addWidget(self.label_piezo_samples_to_plot)
        self.hSB_piezo_samples_to_plot = QtWidgets.QScrollBar(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hSB_piezo_samples_to_plot.sizePolicy().hasHeightForWidth())
        self.hSB_piezo_samples_to_plot.setSizePolicy(sizePolicy)
        self.hSB_piezo_samples_to_plot.setMinimum(2)
        self.hSB_piezo_samples_to_plot.setMaximum(500)
        self.hSB_piezo_samples_to_plot.setSingleStep(2)
        self.hSB_piezo_samples_to_plot.setProperty("value", 100)
        self.hSB_piezo_samples_to_plot.setOrientation(QtCore.Qt.Horizontal)
        self.hSB_piezo_samples_to_plot.setObjectName("hSB_piezo_samples_to_plot")
        self.horizontalLayout_8.addWidget(self.hSB_piezo_samples_to_plot)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.cB_trajectory_name = QtWidgets.QComboBox(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_trajectory_name.sizePolicy().hasHeightForWidth())
        self.cB_trajectory_name.setSizePolicy(sizePolicy)
        self.cB_trajectory_name.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cB_trajectory_name.setFont(font)
        self.cB_trajectory_name.setEditable(True)
        self.cB_trajectory_name.setObjectName("cB_trajectory_name")
        self.horizontalLayout_8.addWidget(self.cB_trajectory_name)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(1270, 1074, 271, 125))
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(4)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget8.setGeometry(QtCore.QRect(0, -3, 273, 129))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout.setObjectName("gridLayout")
        self.pB_fl_paw_add_frame = QtWidgets.QPushButton(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_fl_paw_add_frame.setFont(font)
        self.pB_fl_paw_add_frame.setObjectName("pB_fl_paw_add_frame")
        self.gridLayout.addWidget(self.pB_fl_paw_add_frame, 0, 0, 1, 1)
        self.pB_fl_paw_remove_frame = QtWidgets.QPushButton(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_fl_paw_remove_frame.setFont(font)
        self.pB_fl_paw_remove_frame.setObjectName("pB_fl_paw_remove_frame")
        self.gridLayout.addWidget(self.pB_fl_paw_remove_frame, 0, 1, 1, 1)
        self.cB_fl_paw_frames = QtWidgets.QComboBox(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cB_fl_paw_frames.setFont(font)
        self.cB_fl_paw_frames.setObjectName("cB_fl_paw_frames")
        self.gridLayout.addWidget(self.cB_fl_paw_frames, 1, 1, 1, 1)
        self.label_fl_paw_frames = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_fl_paw_frames.setFont(font)
        self.label_fl_paw_frames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fl_paw_frames.setObjectName("label_fl_paw_frames")
        self.gridLayout.addWidget(self.label_fl_paw_frames, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(1548, 1076, 263, 119))
        self.frame_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(4)
        self.frame_9.setObjectName("frame_9")
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_9)
        self.layoutWidget9.setGeometry(QtCore.QRect(2, -3, 259, 125))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pB_fr_paw_add_frame = QtWidgets.QPushButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_fr_paw_add_frame.setFont(font)
        self.pB_fr_paw_add_frame.setObjectName("pB_fr_paw_add_frame")
        self.gridLayout_2.addWidget(self.pB_fr_paw_add_frame, 0, 0, 1, 1)
        self.pB_fr_paw_remove_frame = QtWidgets.QPushButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_fr_paw_remove_frame.setFont(font)
        self.pB_fr_paw_remove_frame.setObjectName("pB_fr_paw_remove_frame")
        self.gridLayout_2.addWidget(self.pB_fr_paw_remove_frame, 0, 1, 1, 1)
        self.cB_fr_paw_frames = QtWidgets.QComboBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cB_fr_paw_frames.setFont(font)
        self.cB_fr_paw_frames.setObjectName("cB_fr_paw_frames")
        self.gridLayout_2.addWidget(self.cB_fr_paw_frames, 1, 1, 1, 1)
        self.label_fr_paw_frames = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_fr_paw_frames.setFont(font)
        self.label_fr_paw_frames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fr_paw_frames.setObjectName("label_fr_paw_frames")
        self.gridLayout_2.addWidget(self.label_fr_paw_frames, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(1270, 1202, 269, 121))
        self.frame_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(4)
        self.frame_10.setObjectName("frame_10")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(-2, -6, 271, 133))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pB_bl_paw_add_frame = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_bl_paw_add_frame.setFont(font)
        self.pB_bl_paw_add_frame.setObjectName("pB_bl_paw_add_frame")
        self.gridLayout_3.addWidget(self.pB_bl_paw_add_frame, 0, 0, 1, 1)
        self.pB_bl_paw_remove_frame = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_bl_paw_remove_frame.setFont(font)
        self.pB_bl_paw_remove_frame.setObjectName("pB_bl_paw_remove_frame")
        self.gridLayout_3.addWidget(self.pB_bl_paw_remove_frame, 0, 1, 1, 1)
        self.cB_bl_paw_frames = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cB_bl_paw_frames.setFont(font)
        self.cB_bl_paw_frames.setObjectName("cB_bl_paw_frames")
        self.gridLayout_3.addWidget(self.cB_bl_paw_frames, 1, 1, 1, 1)
        self.label_bl_paw_frames = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bl_paw_frames.setFont(font)
        self.label_bl_paw_frames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bl_paw_frames.setObjectName("label_bl_paw_frames")
        self.gridLayout_3.addWidget(self.label_bl_paw_frames, 1, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(1548, 1200, 261, 123))
        self.frame_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(4)
        self.frame_11.setObjectName("frame_11")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_11)
        self.layoutWidget_3.setGeometry(QtCore.QRect(2, 0, 259, 121))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pB_br_paw_add_frame = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_br_paw_add_frame.setFont(font)
        self.pB_br_paw_add_frame.setObjectName("pB_br_paw_add_frame")
        self.gridLayout_4.addWidget(self.pB_br_paw_add_frame, 0, 0, 1, 1)
        self.pB_br_paw_remove_frame = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_br_paw_remove_frame.setFont(font)
        self.pB_br_paw_remove_frame.setObjectName("pB_br_paw_remove_frame")
        self.gridLayout_4.addWidget(self.pB_br_paw_remove_frame, 0, 1, 1, 1)
        self.cB_br_paw_frames = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cB_br_paw_frames.setFont(font)
        self.cB_br_paw_frames.setObjectName("cB_br_paw_frames")
        self.gridLayout_4.addWidget(self.cB_br_paw_frames, 1, 1, 1, 1)
        self.label_br_paw_frames = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_br_paw_frames.setFont(font)
        self.label_br_paw_frames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_br_paw_frames.setObjectName("label_br_paw_frames")
        self.gridLayout_4.addWidget(self.label_br_paw_frames, 1, 0, 1, 1)
        self.label_paw_touch_frames = QtWidgets.QLabel(self.centralwidget)
        self.label_paw_touch_frames.setGeometry(QtCore.QRect(1442, 1026, 231, 43))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_paw_touch_frames.setFont(font)
        self.label_paw_touch_frames.setObjectName("label_paw_touch_frames")
        self.layoutWidget10 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mplg_frames = MplGraphQt5Widget(self.centralwidget)
        self.mplg_frames.setGeometry(QtCore.QRect(-14, -12, 1639, 787))
        self.mplg_frames.setObjectName("mplg_frames")
        self.mplg_piezos = MplGraphQt5Widget(self.centralwidget)
        self.mplg_piezos.setGeometry(QtCore.QRect(-14, 750, 1639, 235))
        self.mplg_piezos.setProperty("spCols", 8)
        self.mplg_piezos.setObjectName("mplg_piezos")
        RatShuttlingPawEventsGenerator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RatShuttlingPawEventsGenerator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1815, 31))
        self.menubar.setObjectName("menubar")
        RatShuttlingPawEventsGenerator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RatShuttlingPawEventsGenerator)
        self.statusbar.setObjectName("statusbar")
        RatShuttlingPawEventsGenerator.setStatusBar(self.statusbar)

        self.retranslateUi(RatShuttlingPawEventsGenerator)
        self.cB_trial_start_frames.setCurrentIndex(-1)
        self.pB_PrevFrame.released.connect(self.sBox_FrameNum.stepDown)
        self.pB_NextFrame.released.connect(self.sBox_FrameNum.stepUp)
        QtCore.QMetaObject.connectSlotsByName(RatShuttlingPawEventsGenerator)

    def retranslateUi(self, RatShuttlingPawEventsGenerator):
        _translate = QtCore.QCoreApplication.translate
        RatShuttlingPawEventsGenerator.setWindowTitle(_translate("RatShuttlingPawEventsGenerator", "Rat Shuttling Paw Events Generator"))
        self.pB_Run.setText(_translate("RatShuttlingPawEventsGenerator", "Run"))
        self.pB_Stop.setText(_translate("RatShuttlingPawEventsGenerator", "Pause"))
        self.label_updates_sec.setText(_translate("RatShuttlingPawEventsGenerator", "Updates\n"
"per sec"))
        self.pB_selecet_data.setText(_translate("RatShuttlingPawEventsGenerator", "Select Data\n"
"Directory"))
        self.label_data_loaded.setText(_translate("RatShuttlingPawEventsGenerator", "No Data\n"
"Loaded"))
        self.label_FrameNum.setText(_translate("RatShuttlingPawEventsGenerator", "Frame Number:"))
        self.pB_PrevFrame.setText(_translate("RatShuttlingPawEventsGenerator", "Previous Frame"))
        self.pB_NextFrame.setText(_translate("RatShuttlingPawEventsGenerator", "Next Frame"))
        self.label_frames_step.setText(_translate("RatShuttlingPawEventsGenerator", "Frame Step Size:"))
        self.label_frame_resize.setText(_translate("RatShuttlingPawEventsGenerator", "Frame resize\n"
"factor"))
        self.pB_add_trial.setText(_translate("RatShuttlingPawEventsGenerator", "Add Current Trial\n"
"To Selected List"))
        self.pB_remove_trial.setText(_translate("RatShuttlingPawEventsGenerator", "Remove Shown Trial From\n"
"Selected List"))
        self.label_selected_trials.setText(_translate("RatShuttlingPawEventsGenerator", "Selected\n"
"Trials"))
        self.pB_goto_trial_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Go To Trial\n"
"Start Frame"))
        self.label_trial_number_txt.setText(_translate("RatShuttlingPawEventsGenerator", "Current \n"
"Trial"))
        self.label_trial_number_int.setText(_translate("RatShuttlingPawEventsGenerator", "-1"))
        self.label_trial_start_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Trials\n"
"Start Frames"))
        self.label_piezo_samples_to_plot.setText(_translate("RatShuttlingPawEventsGenerator", "Number of Ploted Piezo Samples"))
        self.label.setText(_translate("RatShuttlingPawEventsGenerator", "Current Trajectory Name"))
        self.pB_fl_paw_add_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Add Front\n"
"Left Paw"))
        self.pB_fl_paw_remove_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Remove Front\n"
"Left Paw"))
        self.label_fl_paw_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Frames of\n"
"FL Paw"))
        self.pB_fr_paw_add_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Add Front\n"
"Right Paw"))
        self.pB_fr_paw_remove_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Remove Front\n"
"Right Paw"))
        self.label_fr_paw_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Frames of\n"
"FR Paw"))
        self.pB_bl_paw_add_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Add Back\n"
"Left Paw"))
        self.pB_bl_paw_remove_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Remove Back\n"
"Left Paw"))
        self.label_bl_paw_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Frames of\n"
"BL Paw"))
        self.pB_br_paw_add_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Add Back\n"
"Right Paw"))
        self.pB_br_paw_remove_frame.setText(_translate("RatShuttlingPawEventsGenerator", "Remove Back\n"
"Right Paw"))
        self.label_br_paw_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Frames of\n"
"BR Paw"))
        self.label_paw_touch_frames.setText(_translate("RatShuttlingPawEventsGenerator", "Adding Paw Touch Frames"))

from mplgraphqt5widget import MplGraphQt5Widget
